service: aws-java-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: target/java-lambda-dev.jar

functions:
  currentTime:
    handler: com.ds.Handler
