service: sls-java


provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: "20201221"


package:
  artifact: target/java-lambda-dev.jar

functions:
  sample:
    handler: com.ds.Handler
    environment:
      CREATE_TOPIC: true
